# Development overrides — automatically merged by `docker compose up`
# These settings override docker-compose.yml for local development.
version: "3.9"

services:

  auth-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  product-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  image-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  payment-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development