<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ProtoRoot>Protos</ProtoRoot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Tools" Version="2.62.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Google.Protobuf" Version="3.26.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.62.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\common.proto" GrpcServices="Both" />
    <Protobuf Include="Protos\auth.proto" GrpcServices="Both" />
    <Protobuf Include="Protos\product.proto" GrpcServices="Both" />
    <Protobuf Include="Protos\image.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
